### ISSUE TITLE
Deploys that roll the blobstore VM sometimes take a long time

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/capi-release#88] opened 2018-05-22 17:08 UTC
## Issue

In one of our environments deploying CF with internal blobstore, sometimes, when the blobstore VM  is updated, it takes a really long time to update it (30-45 min).

## Possible causes

We think this happens because the `pre-start` script for the `blobstore` job does a [recursive chown of all persistent and ephemeral disk directories](https://github.com/cloudfoundry/capi-release/blob/5871b46f4485740e96be78c62b1cdea545d6dfad/jobs/blobstore/templates/pre-start.sh.erb#L20). Since BOSH doesn't have a timeout for this script, it will take as long as it takes to do a recursive operation on these directories.

Our persistent and ephemeral disks seem pretty empty:
```
# df -ah
/dev/sda3       3.5G  828M  2.5G  25% /var/vcap/data
/dev/sda3       3.5G  828M  2.5G  25% /var/log
tmpfs           1.0M   20K 1004K   2% /var/vcap/data/sys/run
/dev/sda3       3.5G  828M  2.5G  25% /tmp
/dev/sda3       3.5G  828M  2.5G  25% /var/tmp
/dev/sda1       2.8G  1.3G  1.4G  47% /home
/dev/sdb1        99G   11G   83G  12% /var/vcap/store
```

## Steps to Reproduce

Run a bosh deploy that will result in a blobstore roll (e.g. stemcell update). The blobstore persistent disk must have some data in it in order to see elevated deploy times.

## Expected result

It would be great if this operation was smarter and could take less time every time you deploy, as it is causing quite significant app pushability downtime.

## Current result

It takes 30-45 min to update the blobstore VM.

**Comment by Gerg** [comment] 2018-07-06 00:46
I believe this is a duplicate of https://github.com/cloudfoundry/cloud_controller_ng/issues/1013. It should be fixed in https://github.com/cloudfoundry/capi-release/commit/3ab36af3d5f77b781fcfa3b0a8f965cf11ac5a3e

**Closed by Gerg** 2018-07-06 00:46 UTC
Labels: unscheduled
