### ISSUE TITLE
Property "perform_blob_cleanup" missing on cloud_controller_clock

### ISSUE THREAD

**Issue by renelehmann** [cloudfoundry/capi-release#167] opened 2020-03-03 16:58 UTC
## Issue
Error due a missing config property on cloud_controller_clock.

```
/var/vcap/sys/log/cloud_controller_clock/cloud_controller_clock.stdout.log:
I, [2020-02-17T01:30:00.001992 #7]  INFO -- : Triggering 'orphaned_blobs_cleanup.job'
E, [2020-02-17T01:30:00.102811 #7] ERROR -- : "perform_blob_cleanup" is not a valid config key (VCAP::CloudController::Config::InvalidConfigPath)
```

## Context
Using cf-deployment (cloudfoundry open source) a defined "scheduler" instance group consist of a "cloud_controller_clock" job. 
The cc property "perform_blob_cleanup" for the cloud_controller_clock job spec/templates is missing on the capi-release (develop: 6141bea ; master: 29b9b38)

This property is defined on the cloud_controller_worker spec/templates but not for the clock job:
```
  cc.perform_blob_cleanup:
    description: "Whether or not to perform the blob cleanup job"
    default: true
```

**Comment by aashah** [comment] 2020-04-29 21:09
That's interesting. The blob cleanup job does not run on the clock VM, so I'm not totally positive how that error could be emitted from that file. I don't think we'll add the property to the clock's `spec` file for that reason. Will definitely explore this a bit further.

**Comment by selzoc** [comment] 2020-07-30 22:03
Hi @renelehmann we're not able to reproduce this and as @aashah mentioned this job doesn't actually run on the clock, but on the worker.  Closing for now, please reopen if you feel differently.

**Closed by selzoc** 2020-07-30 22:03 UTC
Labels: unscheduled
